version: '3.10.12'

volumes:
  media:
  static:
  foodgram_db:

services:
  db:
    environment:
      - POSTGRES_PASSWORD=foodgram_password
      - POSTGRES_DB=foodgram
      - POSTGRES_USER=foodgram_user
    image: postgres:13
    volumes:
      - foodgram_db:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    build: ../backend/foodgram/
    env_file: .env
    volumes:    
      - static:/app/collected_static/
      - media:/app/media/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    depends_on:
      - backend
    image: nginx:1.22.1
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/var/html/media/
      - static:/static/